<?php

/**
 * @file
 * Provides hooks for registration tests.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\registration\Entity\RegistrationInterface;

/**
 * Implements hook_entity_base_field_info().
 */
function registration_test_entity_base_field_info(EntityTypeInterface $entity_type): array {
  $fields = [];
  // Add a base registration field to node entities.
  if ($entity_type->id() === 'node') {
    // Default to enabled with capacity 5 and max of 2 spaces per registration.
    $default_settings = [
      'status' => [
        'value' => TRUE,
      ],
      'capacity' => [
        0 => [
          'value' => 5,
        ],
      ],
      'maximum_spaces' => [
        0 => [
          'value' => 2,
        ],
      ],
      'from_address' => [
        0 => [
          'value' => 'test@example.com',
        ],
      ],
    ];
    $fields['event_registration'] = BaseFieldDefinition::create('registration')
      ->setLabel(t('Registration'))
      ->setDefaultValue([
        'registration_settings' => serialize($default_settings),
      ]);
  }
  return $fields;
}

/**
 * Implements hook_registration_presave().
 */
function registration_test_registration_presave(RegistrationInterface $registration) {
  if ($registration->getAnonymousEmail() == 'trigger_presave_hook@example.org') {
    $registration->set('state', 'complete');
  }
}
