<?php

/**
 * @file
 * Provides user regigistration for events.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\Entity\EntityFormDisplay;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Link;
use Drupal\Core\Render\Element;
use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_entity_extra_field_info().
 *
 * @see function registration_registration_view().
 */
function registration_entity_extra_field_info() {
  // Add extra display fields for calculated registration data.
  $extra = [];
  $registration_types = \Drupal::service('entity_type.bundle.info')->getBundleInfo('registration');
  foreach ($registration_types as $type => $info) {
    $extra['registration'][$type]['display']['email_address'] = [
      'label' => t('Email address'),
      'description' => t('Registrant email address pseudo field.'),
      'weight' => 0,
      'visible' => TRUE,
    ];
    $extra['registration'][$type]['display']['host_entity'] = [
      'label' => t('Host entity'),
      'description' => t('Host entity pseudo field.'),
      'weight' => 0,
      'visible' => TRUE,
    ];
  }
  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 *
 * @see function registration_entity_extra_field_info().
 */
function registration_registration_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // Determine the label display to use for extra fields by looking at others.
  $label_display = 'above';
  $components = $display->getComponents();
  foreach ($components as $id => $component) {
    if ($id != 'anon_mail') {
      if (!empty($component['label'])) {
        $label_display = $component['label'];
        break;
      }
    }
  }

  // Add the extra fields.
  if ($display->getComponent('email_address')) {
    $build['email_address'] = [
      '#theme' => 'field',
      '#label_display' => $label_display,
      '#view_mode' => '_custom',
      '#title' => t('Email address'),
      '#field_type' => 'text',
      '#field_name' => 'email_address',
      '#bundle' => $entity->bundle(),
      '#entity_type' => $entity->getEntityTypeId(),
      '#object' => $entity,
      '#is_multiple' => FALSE,
      '#items' => [],
      0 => [
        '#markup' => $entity->getEmail(),
      ],
    ];
  }
  if ($display->getComponent('host_entity')) {
    if ($host_entity = $entity->getHostEntity()) {
      $build['host_entity'] = [
        '#theme' => 'field',
        '#label_display' => $label_display,
        '#view_mode' => '_custom',
        '#title' => $host_entity->getEntityType()->getLabel(),
        '#field_type' => 'text',
        '#field_name' => 'host_entity',
        '#bundle' => $entity->bundle(),
        '#entity_type' => $entity->getEntityTypeId(),
        '#object' => $entity,
        '#is_multiple' => FALSE,
        '#items' => [],
        0 => [
          '#markup' => Link::fromTextAndUrl($host_entity->label(), $host_entity->toUrl())->toString(),
        ],
      ];
    }
  }
}

/**
 * Implements hook_theme().
 */
function registration_theme(): array {
  return [
    'registration_form' => [
      'render element' => 'form',
    ],
    'registration' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for a registration.
 *
 * Default template: registration.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing rendered fields.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_registration(array &$variables) {
  /** @var Drupal\registration\Entity\RegistrationInterface $registration */
  $registration = $variables['elements']['#registration'];

  $variables['registration_entity'] = $registration;
  $variables['registration'] = [];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['registration'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_entity_insert().
 */
function registration_entity_insert(EntityInterface $entity) {
  // Rebuild routes and local tasks when Registration fields are added.
  if ($entity instanceof FieldConfig) {
    if ($entity->getType() == 'registration') {
      \Drupal::service('plugin.manager.menu.local_task')->clearCachedDefinitions();
      \Drupal::service("router.builder")->rebuild();
    }
  }
}

/**
 * Implements hook_entity_delete().
 */
function registration_entity_delete(EntityInterface $entity) {
  // Delete registrations and settings for this host entity.
  \Drupal::database()->delete('registration')
    ->condition('entity_type_id', $entity->getEntityTypeId())
    ->condition('entity_id', $entity->id())
    ->execute();
  \Drupal::database()->delete('registration_entity')
    ->condition('entity_type_id', $entity->getEntityTypeId())
    ->condition('entity_id', $entity->id())
    ->execute();

  // Rebuild routes and local tasks when Registration fields are deleted.
  if ($entity instanceof FieldConfig) {
    if ($entity->getType() == 'registration') {
      \Drupal::service('plugin.manager.menu.local_task')->clearCachedDefinitions();
      \Drupal::service("router.builder")->rebuild();
    }
  }
}

/**
 * Implements hook_entity_update().
 */
function registration_entity_update(EntityInterface $entity) {
  // If a form display for a registration field is updated, clear
  // the local task plugin cache so local tasks (tabs) are rebuilt,
  // in case the Hide Register Tab field setting may have changed.
  if ($entity instanceof EntityFormDisplay) {
    $entity_types = \Drupal::entityTypeManager()->getDefinitions();
    $entity_type = $entity_types[$entity->getTargetEntityTypeId()];
    if (\Drupal::service('registration.manager')->hasRegistrationField($entity_type)) {
      \Drupal::service('plugin.manager.menu.local_task')->clearCachedDefinitions();
    }
  }
}
