<?php

/**
 * @file
 * Provides user regigistration for events.
 */

use Drupal\Core\Entity\Entity\EntityFormDisplay;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function registration_theme(): array {
  return [
    'registration_form' => [
      'render element' => 'form',
    ],
    'registration' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for a registration.
 *
 * Default template: registration.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing rendered fields.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_registration(array &$variables) {
  /** @var Drupal\registration\Entity\RegistrationInterface $registration */
  $registration = $variables['elements']['#registration'];

  $variables['registration_entity'] = $registration;
  $variables['registration'] = [];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['registration'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_entity_update().
 */
function registration_entity_update(EntityInterface $entity) {
  // If a form display for a registration field is updated, clear
  // the local task plugin cache so local tasks (tabs) are rebuilt,
  // in case the Hide Register Tab field setting may have changed.
  if ($entity instanceof EntityFormDisplay) {
    $entity_types = \Drupal::entityTypeManager()->getDefinitions();
    $entity_type = $entity_types[$entity->getTargetEntityTypeId()];
    if (\Drupal::service('registration.service')->hasRegistrationField($entity_type)) {
      \Drupal::service('plugin.manager.menu.local_task')->clearCachedDefinitions();
    }
  }
}
