<?php

/**
 * @file
 * Provides a confirmation message for registrations.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function registration_confirmation_form_registration_type_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $registration_type = $form_state->getFormObject()->getEntity();

  $form['registration_confirmation'] = [
    '#type' => 'details',
    '#title' => t('Confirmation email settings'),
    '#description' => t('This applies when a user is fully registered to the event.'),
  ];
  $form['registration_confirmation']['registrant_email'] = [
    '#type' => 'details',
    '#title' => t('Confirmation email for the registrant'),
    '#open' => TRUE,
  ];
  $form['registration_confirmation']['registrant_email']['enable'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable confirmation email for registrant'),
    '#default_value' => $registration_type->getThirdPartySetting('registration_confirmation', 'registrant_email_enable'),
  ];
  $form['registration_confirmation']['registrant_email']['subject'] = [
    '#type' => 'textfield',
    '#title' => t('Subject'),
    '#default_value' => $registration_type->getThirdPartySetting('registration_confirmation', 'registrant_email_subject'),
    '#states' => [
      'required' => [
        ':input[name="registration_confirmation[registrant_email][enable]"]' => ['checked' => TRUE],
      ],
      'visible' => [
        ':input[name="registration_confirmation[registrant_email][enable]"]' => ['checked' => TRUE],
      ],
    ],
  ];
  $message = $registration_type->getThirdPartySetting('registration_confirmation', 'registrant_email_message');
  $form['registration_confirmation']['registrant_email']['message'] = [
    '#type' => 'text_format',
    '#title' => t('Message'),
    '#description' => t('Enter the message you want to send. Tokens are supported, e.g., [node:title].'),
    '#default_value' => $message['value'] ?? '',
    '#format' => $message['format'] ?? filter_default_format(),
    '#states' => [
      'visible' => [
        ':input[name="registration_confirmation[registrant_email][enable]"]' => ['checked' => TRUE],
      ],
    ],
  ];
  $form['registration_confirmation']['admin_email'] = [
    '#type' => 'details',
    '#title' => t('Confirmation email for the admin'),
    '#open' => TRUE,
  ];
  $form['registration_confirmation']['admin_email']['enable'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable confirmation email for admin'),
    '#default_value' => $registration_type->getThirdPartySetting('registration_confirmation', 'admin_email_enable'),
  ];
  $form['registration_confirmation']['admin_email']['admin_email_address'] = [
    '#type' => 'email',
    '#title' => t('Admin e-mail address'),
    '#states' => [
      'visible' => [
        ':input[name="registration_confirmation[admin_email][enable]"]' => ['checked' => TRUE],
      ],
    ],
    '#default_value' => $registration_type->getThirdPartySetting('registration_confirmation', 'admin_email_address'),
  ];
  $form['registration_confirmation']['admin_email']['send_registrant_confirmation_copy'] = [
    '#type' => 'checkbox',
    '#title' => t('Send copy of registrant confirmation email'),
    '#description' => 'Leave unchecked for custom message.',
    '#states' => [
      'visible' => [
        ':input[name="registration_confirmation[admin_email][enable]"]' => ['checked' => TRUE],
      ],
    ],
    '#default_value' => $registration_type->getThirdPartySetting('registration_confirmation', 'send_registrant_confirmation_copy'),
  ];
  $form['registration_confirmation']['admin_email']['subject'] = [
    '#type' => 'textfield',
    '#title' => t('Subject'),
    '#default_value' => $registration_type->getThirdPartySetting('registration_confirmation', 'admin_email_subject'),
    '#states' => [
      'required' => [
        ':input[name="registration_confirmation[admin_email][enable]"]' => ['checked' => TRUE],
        'and',
        ':input[name="registration_confirmation[admin_email][send_registrant_confirmation_copy]"]' => ['checked' => FALSE],
      ],
      'visible' => [
        ':input[name="registration_confirmation[admin_email][send_registrant_confirmation_copy]"]' => ['checked' => FALSE],
        'and',
        ':input[name="registration_confirmation[admin_email][enable]"]' => ['checked' => TRUE],
      ],
    ],
  ];
  $message = $registration_type->getThirdPartySetting('registration_confirmation', 'admin_email_message');
  $form['registration_confirmation']['admin_email']['message'] = [
    '#type' => 'text_format',
    '#title' => t('Message'),
    '#description' => t('Enter the message you want to send. Tokens are supported, e.g., [node:title].'),
    '#default_value' => $message['value'] ?? '',
    '#format' => $message['format'] ?? filter_default_format(),
    '#states' => [
      'visible' => [
        ':input[name="registration_confirmation[admin_email][send_registrant_confirmation_copy]"]' => ['checked' => FALSE],
        'and',
        ':input[name="registration_confirmation[admin_email][enable]"]' => ['checked' => TRUE],
      ],
    ],
  ];
  if (\Drupal::moduleHandler()->moduleExists('token')) {
    $form['token_tree'] = [
      '#theme' => 'token_tree_link',
      '#token_types' => [
        'registration',
        'registration_settings',
      ],
      '#global_types' => FALSE,
      '#weight' => 10,
    ];
    /** @var \Drupal\registration\RegistrationManagerInterface $registration_manager */
    $registration_manager = \Drupal::service('registration.manager');
    foreach ($registration_manager->getRegistrationEnabledEntityTypes() as $entity_type) {
      $form['token_tree']['#token_types'][] = $entity_type->id();
    }
  }
  $form['actions']['submit']['#submit'][] = 'registration_confirmation_form_registration_type_submit';
}

/**
 * Implements submit handler for hook_form_BASE_FORM_ID_alter().
 */
function registration_confirmation_form_registration_type_submit(&$form, FormStateInterface $form_state) {
  $registration_type = $form_state->getFormObject()->getEntity();
  $registration_type->setThirdPartySetting('registration_confirmation', 'registrant_email_enable', $form_state->getValue([
    'registration_confirmation',
    'registrant_email',
    'enable',
  ]));
  $registration_type->setThirdPartySetting('registration_confirmation', 'registrant_email_subject', $form_state->getValue([
    'registration_confirmation',
    'registrant_email',
    'subject',
  ]));
  $registration_type->setThirdPartySetting('registration_confirmation', 'registrant_email_message', $form_state->getValue([
    'registration_confirmation',
    'registrant_email',
    'message',
  ]));
  $registration_type->setThirdPartySetting('registration_confirmation', 'admin_email_enable', $form_state->getValue([
    'registration_confirmation',
    'admin_email',
    'enable',
  ]));
  $registration_type->setThirdPartySetting('registration_confirmation', 'admin_email_address', $form_state->getValue([
    'registration_confirmation',
    'admin_email',
    'admin_email_address',
  ]));
  $registration_type->setThirdPartySetting('registration_confirmation', 'admin_email_subject', $form_state->getValue([
    'registration_confirmation',
    'admin_email',
    'subject',
  ]));
  $registration_type->setThirdPartySetting('registration_confirmation', 'admin_email_message', $form_state->getValue([
    'registration_confirmation',
    'admin_email',
    'message',
  ]));
  $registration_type->setThirdPartySetting('registration_confirmation', 'send_registrant_confirmation_copy', $form_state->getValue([
    'registration_confirmation',
    'admin_email',
    'send_registrant_confirmation_copy',
  ]));
  $registration_type->save();
}
