# Schema for the configuration files of the Registration Waitlist module.

registration.type.*.third_party.registration_waitlist:
  type: mapping
  label: 'Wait list confirmation email settings'
  mapping:
    registrant_email:
      type: mapping
      label: 'Registrant confirmation mail settings'
      mapping:
        confirmation_registrant_email_enable:
          label: 'Enable registrant confirmation email'
          type: boolean
        confirmation_registrant_email_subject:
          label: 'Registrant confirmation email subject'
          type: string
        confirmation_registrant_email_message:
          label: 'Registrant confirmation email message'
          type: text_format
    admin_email:
      type: mapping
      label: 'Admin confirmation mail settings'
      mapping:
        confirmation_admin_email_enable:
          label: 'Enable admin confirmation email'
          type: boolean
        admin_email_address:
          label: 'Admin e-mail address'
          type: email
        confirmation_admin_email_subject:
          label: 'Admin confirmation email subject'
          type: string
        confirmation_admin_email_message:
          label: 'Admin confirmation email message'
          type: text_format
        send_registrant_confirmation_copy:
          label: 'Send copy of registrant confirmation message to the admin'
          type: boolean
